Repository puppetlabs/puppetlabs-peadm, pull requests merged in 2021-09, with the labels that each got.

#201 Add PE download signature checking
  tasks/download.json
  tasks/download.sh
Labels: feature

#203 Support PE 2021.3
  .github/workflows/test-add-replica.yaml
  .github/workflows/test-install-matrix.yaml
  .github/workflows/test-install.yaml
  README.md
  functions/assert_supported_bolt_version.pp
  functions/assert_supported_pe_version.pp
Labels: feature

#207 Improve download task gpg verification
  tasks/download.json
  tasks/download.sh
Labels: maintenance

#208 Release prep for v3.1.0
  CHANGELOG.md
  metadata.json
  spec/plans/uninstall_spec.rb
Labels: maintenance

#210 PDK 2.2.0 update
  .github/workflows/auto_release.yml
  .gitlab-ci.yml
  .travis.yml
  Rakefile
  appveyor.yml
  metadata.json
  pdk.yaml
Labels: maintenance

#199 Make PEAdm a Puppet supported module
  README.md
Labels: feature

#211 Add auto-generated REFERENCE.md documentation
  REFERENCE.md
  functions/assert_supported_architecture.pp
  functions/assert_supported_bolt_version.pp
  functions/assert_supported_pe_version.pp
  functions/certname.pp
  manifests/setup/convert_node_manager.pp
  manifests/setup/convert_pre20197.pp
  manifests/setup/node_manager.pp
  manifests/setup/node_manager_yaml.pp
  plans/convert.pp
  plans/install.pp
  plans/modify_certificate.pp
  plans/status.pp
  plans/upgrade.pp
Labels: feature

#213 Update documentation to reference supported PE version
  documentation/install.md
Labels: bugfix

#215 Improve reliability of downloading PE tarball
  tasks/download.sh
Labels: bugfix

#204 Add development and testing option to permit installing unsupported PE versions
  functions/assert_supported_pe_version.pp
  plans/install.pp
  plans/subplans/install.pp
  plans/upgrade.pp
  spec/functions/assert_supported_pe_version_spec.rb
Labels: feature
