Repository puppetlabs/puppetlabs-peadm, pull requests merged in 2023-02, with the labels that each got.

#323 Locking changelog_generator gem version
  .sync.yml
Labels: maintenance

#324 changelog_generator gemfile update
  Gemfile
  metadata.json
Labels: maintenance

#317 Fail with guidance if peadm::util::retrieve_and_upload is used on PE XL with the PCP transport
  REFERENCE.md
  functions/fail_on_transport.pp
  plans/subplans/modify_certificate.pp
  plans/upgrade.pp
  plans/util/retrieve_and_upload.pp
  spec/functions/fail_on_transport_spec.rb
  spec/plans/subplans/modify_certificate_spec.rb
  spec/plans/upgrade_spec.rb
  spec/plans/util/retrieve_and_upload_spec.rb
Labels: feature

#331 fix variable notation
  plans/subplans/db_populate.pp
Labels: maintenance

#333 switch to dev tools container and update changelog generator
  .github/workflows/auto_release.yml
  .sync.yml
Labels: maintenance

#337 Remove experimental backup/restore plans
  documentation/backup.md
  documentation/restore.md
  plans/backup.pp
  plans/restore.pp
  spec/plans/backup_spec.rb
  spec/plans/restore_spec.rb
Labels: feature

#336 Fix group letter assignments during upgrade
  .github/workflows/test-failover.yaml
  .gitignore
  functions/assert_supported_architecture.pp
  functions/assert_supported_pe_version.pp
  plans/add_replica.pp
  plans/modify_certificate.pp
  plans/subplans/install.pp
  plans/subplans/modify_certificate.pp
  plans/subplans/prepare_agent.pp
  plans/upgrade.pp
  spec/acceptance/peadm_spec/plans/add_replica.pp
  spec/acceptance/peadm_spec/plans/install_test_cluster.pp
  spec/acceptance/peadm_spec/plans/perform_failover.pp
  spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
  spec/acceptance/peadm_spec/plans/upgrade_test_cluster.pp
  spec/acceptance/peadm_spec/tasks/delete_certname.json
  spec/acceptance/peadm_spec/tasks/delete_certname.sh
  spec/plans/add_replica_spec.rb
  spec/plans/modify_certificate_spec.rb
  tasks/provision_replica.sh
  tasks/rbac_token.rb
Labels: bugfix
