Repository puppetlabs/puppetlabs-peadm, pull requests merged in 2023-06, with the labels that each got.

#361 Update metadata for stdlib version 9
  metadata.json
Labels: enhancement

#368 (MAINT) Stop CI from triggering twice
  .github/workflows/test-fips-install-matrix.yaml
  .github/workflows/test-install-matrix.yaml
  .github/workflows/test-upgrade-matrix.yaml
Labels: maintenance

#367 (#366) Bump inifile and stdlib
  metadata.json
Labels: bug
