Repository puppetlabs/puppetlabs-peadm, pull requests merged in 2024-08, with the labels that each got.

#466 pe_installer_source: Use Stdlib::HTTPSUrl datatype
  REFERENCE.md
  plans/install.pp
  plans/subplans/install.pp
  plans/upgrade.pp
Labels: feature

#472 (MAINT) update mend workflow to use shared tooling
  .github/workflows/mend.yml
Labels: maintenance

#445 Add Ubuntu 22.04 support
  metadata.json
Labels: maintenance

#444 Add AlmaLinux/CentOS 9 support
  metadata.json
Labels: maintenance

#479 (#469) Assign correct environment to node groups
  REFERENCE.md
  functions/get_node_group_environment.pp
  manifests/setup/node_manager.pp
  plans/add_database.pp
  plans/add_replica.pp
  plans/convert.pp
  plans/install.pp
  plans/subplans/configure.pp
  plans/upgrade.pp
  plans/util/update_classification.pp
  spec/functions/get_node_group_environment_spec.rb
  spec/plans/convert_spec.rb
  spec/plans/install_spec.rb
  spec/plans/upgrade_spec.rb
Labels: bugfix
