Repository puppetlabs/puppetlabs-peadm, pull requests merged in 2024-12, with the labels that each got.

#525 Move download_type enum to own type alias
  REFERENCE.md
  plans/install.pp
  plans/subplans/install.pp
  plans/upgrade.pp
  types/download_mode.pp
Labels: feature

#529 Add support for bolt 4.x
  functions/assert_supported_bolt_version.pp
Labels: bugfix

#531 (PE-39351) Update add_database plan to work with patching/HAC
  REFERENCE.md
  functions/pe_db_names.pp
  plans/add_database.pp
Labels: maintenance
